import { browser } from '$app/environment';

export function registerServiceWorker() {
  if (!browser || !('serviceWorker' in navigator)) return;

  // Wait for page load
  if (document.readyState === 'loading') {
    window.addEventListener('load', () => {
      registerSW();
    });
  } else {
    registerSW();
  }
}

function registerSW() {
  if (!browser || !('serviceWorker' in navigator)) return;

  // Try to use vite-plugin-pwa register if available (will be generated by plugin)
  // Fallback to manual registration
  const swPath = '/sw.js';
  
  navigator.serviceWorker
    .register(swPath, {
      scope: '/'
    })
    .then((registration: ServiceWorkerRegistration) => {
      console.log('Service Worker registered:', registration);
      
      // Setup notification click handler
      if ('serviceWorker' in navigator && navigator.serviceWorker.controller) {
        navigator.serviceWorker.addEventListener('message', (event) => {
          if (event.data && event.data.type === 'notificationclick') {
            const notificationData = event.data.data;
            if (notificationData && notificationData.url) {
              window.location.href = notificationData.url;
            }
          }
        });
      }
      
      // Check for updates periodically
      setInterval(() => {
        registration.update();
      }, 60 * 60 * 1000); // Check every hour
      
      // Listen for updates
      registration.addEventListener('updatefound', () => {
        const newWorker = registration.installing;
        if (newWorker) {
          newWorker.addEventListener('statechange', () => {
            if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
              // New service worker available
              console.log('New content available, please refresh');
              // You can show a notification to user here
              if (confirm('Update tersedia! Refresh halaman untuk mendapatkan versi terbaru?')) {
                window.location.reload();
              }
            }
          });
        }
      });
    })
    .catch((error: Error) => {
      console.error('Service Worker registration error:', error);
    });
}

export async function requestNotificationPermission(): Promise<NotificationPermission> {
  if (!browser || !('Notification' in window)) {
    return 'denied';
  }

  if (Notification.permission === 'granted') {
    return 'granted';
  }

  if (Notification.permission === 'denied') {
    return 'denied';
  }

  const permission = await Notification.requestPermission();
  return permission;
}

export async function showNotification(title: string, options?: NotificationOptions) {
  if (!browser) {
    return;
  }

  // Check if service worker is available
  if (!('serviceWorker' in navigator)) {
    // Fallback to browser notification if service worker not available
    if ('Notification' in window && Notification.permission === 'granted') {
      new Notification(title, {
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        ...options
      });
    }
    return;
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    
    if (Notification.permission === 'granted') {
      const notificationOptions: any = {
        badge: '/pwa-192x192.png',
        icon: '/pwa-192x192.png',
        tag: options?.tag || 'default',
        requireInteraction: false,
        silent: false,
        vibrate: [200, 100, 200],
        ...options
      };
      
      await registration.showNotification(title, notificationOptions);
    }
  } catch (error) {
    console.error('Error showing notification:', error);
  }
}

export async function showMessageNotification(senderName: string, message: string) {
  // Truncate long messages
  const truncatedMessage = message.length > 50 ? message.substring(0, 50) + '...' : message;
  
  const notificationOptions: any = {
    tag: `message-${senderName}`,
    body: truncatedMessage,
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    data: {
      url: '/chat',
      sender: senderName,
      timestamp: Date.now()
    },
    actions: [
      {
        action: 'open',
        title: 'Buka Chat'
      }
    ],
    renotify: true
  };
  
  await showNotification(`${senderName}`, notificationOptions);
}

