import { browser } from '$app/environment';

export function registerServiceWorker() {
  if (!browser || !('serviceWorker' in navigator)) return;

  // Wait for page load
  if (document.readyState === 'loading') {
    window.addEventListener('load', () => {
      registerSW();
    });
  } else {
    registerSW();
  }
}

function registerSW() {
  if (!browser || !('serviceWorker' in navigator)) return;

  // Try to use vite-plugin-pwa register if available (will be generated by plugin)
  // Fallback to manual registration
  const swPath = '/sw.js';
  
  navigator.serviceWorker
    .register(swPath, {
      scope: '/'
    })
    .then((registration: ServiceWorkerRegistration) => {
      console.log('Service Worker registered:', registration);
      
      // Check for updates periodically
      setInterval(() => {
        registration.update();
      }, 60 * 60 * 1000); // Check every hour
      
      // Listen for updates
      registration.addEventListener('updatefound', () => {
        const newWorker = registration.installing;
        if (newWorker) {
          newWorker.addEventListener('statechange', () => {
            if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
              // New service worker available
              console.log('New content available, please refresh');
              // You can show a notification to user here
              if (confirm('Update tersedia! Refresh halaman untuk mendapatkan versi terbaru?')) {
                window.location.reload();
              }
            }
          });
        }
      });
    })
    .catch((error: Error) => {
      console.error('Service Worker registration error:', error);
    });
}

export async function requestNotificationPermission(): Promise<NotificationPermission> {
  if (!browser || !('Notification' in window)) {
    return 'denied';
  }

  if (Notification.permission === 'granted') {
    return 'granted';
  }

  if (Notification.permission === 'denied') {
    return 'denied';
  }

  const permission = await Notification.requestPermission();
  return permission;
}

export async function showNotification(title: string, options?: NotificationOptions) {
  if (!browser || !('Notification' in window)) {
    return;
  }

  if (Notification.permission === 'granted') {
    const registration = await navigator.serviceWorker.ready;
    registration.showNotification(title, {
      badge: '/pwa-192x192.png',
      icon: '/pwa-192x192.png',
      ...options
    });
  }
}

